#!/usr/bin/python
# --------------------------------------------------------------------------
# Control script for DS3231-RTC
#
# Note that times in the RTC are stored in UTC. You can change this
# behavior by changing the utc-variable to False.
#
# Supported commands
#  help  - dump list of available commands
#  show  - display datetime, alarm1, alarm2, sys or all
#  dump  - display registers (binary format)
#  set   - datetime, alarm1, alarm2, sys times
#  on    - turn alarm1/alarm2 on
#  off   - turn alarm1/alarm2 on
#  clear - clear alarm1/alarm2-flag
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-wake-on-rtc
#
# --------------------------------------------------------------------------

import os, sys. re, datetime

import ds3231

# --- settings   -----------------------------------------------------------

utc=True                    # all times in the RTC are stored as utc
                            # with automatic conversion while reading

# --- help   ---------------------------------------------------------------

def help():
  """
  Dump list of available commands
  """
  print """
Available commands (date and time are synonyms):
     help                                - dump list of available commands
     show  [date|time|alarm1|alarm2|
                               sys|all]  - display given type or all
     dump  [control|status|alarm1|
                           alarm2|all]   - display registers (hex/binary format)
     set   date|time|alarm1|alarm2|sys   - set date/time, alarm1, alarm2 times
                                           Format: dd.mm.YYYY [HH:MM[:SS]] or
                                                   mm/dd.YYYY [HH:MM[:SS]]
                                           (does not turn alarm on!)
     on    alarm1|alarm2                 - turn alarm1/alarm2 on
     off   alarm1|alarm2                 - turn alarm1/alarm2 on
     clear alarm1|alarm2                 - clear alarm1/alarm2-flag
  """

# --- show   ---------------------------------------------------------------

def show(rtc,argv):
  """
  Display date, time, alarm1, alarm2 or all (date and time are synonyms)
  
  Arg: date|time|alarm1|alarm2|sys|all (default: all)
  """
  if len(argv) == 0:
    show(rtc,["date"])
    show(rtc,["alarm1"])
    show(rtc,["alarm2"])
    show(rtc,["sys"])
  elif argv[0] == "date" or argv[0] == "time":
    print "date:   %s" % rtc.read_datetime()
  elif argv[0] == "alarm1":
    print "alarm1: %s" % rtc.get_alarm_time(1)
    (enabled,fired) = rtc.get_alarm_state(1)
    print "        (enabled: %s)" % enabled
    print "        (fired:   %s)" % fired
  elif argv[0] == "alarm2":
    print "alarm2: %s" % rtc.get_alarm_time(2)
    (enabled,fired) = rtc.get_alarm_state(2)
    print "        (enabled: %s)" % enabled
    print "        (fired:   %s)" % fired
  elif argv[0] == "sys":
    print "sys:    %s" % datetime.datetime.now()
  else:
    print "invalid argument"

# --- dump   ---------------------------------------------------------------

def dump(rtc,argv):
  """
  Display registers (hex/binary format)

  Arg: control|status|date|time|alarm1|alarm2|all (default: all)
  """
  if len(argv) == 0:
    dump(rtc,["control"])
    dump(rtc,["status"])
    dump(rtc,["date"])
    dump(rtc,["alarm1"])
    dump(rtc,["alarm2"])
  elif argv[0] == "control":
    print "control:        %s" % rtc.dump_register(rtc._CONTROL_REGISTER)
  elif argv[0] == "status":
    print "status:         %s" % rtc.dump_register(rtc._STATUS_REGISTER)
  elif argv[0] == "date" or argv[0] == "time":
    print "date  (sec):   %s" % rtc.dump_register(rtc._SECONDS_REGISTER)
    print "date  (min):   %s" % rtc.dump_register(rtc._MINUTES_REGISTER)
    print "date  (hour):  %s" % rtc.dump_register(rtc._HOURS_REGISTER)
    print "date  (weekd): %s" % rtc.dump_register(rtc._DAY_OF_WEEK_REGISTER)
    print "date  (day):   %s" % rtc.dump_register(rtc._DAY_OF_MONTH_REGISTER)
    print "date  (month): %s" % rtc.dump_register(rtc._MONTH_REGISTER)
    print "date  (year):  %s" % rtc.dump_register(rtc._YEAR_REGISTER)
  elif argv[0] == "alarm1":
    print "alarm1 (sec):   %s" % rtc.dump_register(rtc._ALARM1_SEC_REGISTER)
    print "alarm1 (min):   %s" % rtc.dump_register(rtc._ALARM1_MIN_REGISTER)
    print "alarm1 (hour):  %s" % rtc.dump_register(rtc._ALARM1_HOUR_REGISTER)
    print "alarm1 (date):  %s" % rtc.dump_register(rtc._ALARM1_DATE_REGISTER)
  elif argv[0] == "alarm2":
    print "alarm2 (min):   %s" % rtc.dump_register(rtc._ALARM2_MIN_REGISTER)
    print "alarm2 (hour):  %s" % rtc.dump_register(rtc._ALARM2_HOUR_REGISTER)
    print "alarm2 (date):  %s" % rtc.dump_register(rtc._ALARM2_DATE_REGISTER)
  else:
    print "invalid argument"

# --- set   ----------------------------------------------------------------

def set(rtc,argv):
  """
  set date, time, alarm1, alarm2 (date and time are synonyms)
  
  Arg: date|time|alarm1|alarm2
  """
  if len(argv) == 0:
    print "missing argument"
  elif argv[0] == "date" or argv[0] == "time":
    rtc.write_system_datetime_now()
  elif argv[0] == "sys":
    dtime = rtc.read_datetime()
    os.system("date -s %s" % dtime)
  if len(argv) == 1:
    print "missing argument"
    return

  dateString = argv[1] + (" " + argv[2] if len(argv) > 2 else "")
  if '/' in dateString:
    format = "%m/%d/%Y %H:%M:%S"
  else:
    format = "%d.%m.%Y %H:%M:%S"

  # add default hour:minutes:secs if not provided
  if ':'  not in dateString:
    dateString = dateString + " 00:00:00"

  # parse string and check if we have six items
  dateParts= re.split('\.|/|:| ',dateString)
  count = len(dateParts)
  if count < 5 or count > 6:
    print "illegal datetime format!"
    print "Must be mm/dd/yy[yy] [HH:MM[:SS]] or"
    print "        dd.mm.yy[yy] [HH:MM[:SS]]"
    return
  elif count == 5:
    dateString = dateString + ":00"

  if len(dateParts[2]) == 2:
    format = format.replace('Y','y')

  if argv[0] == "alarm1":
    rtc.set_alarm_time(1,datetime.datetime.strptime(dateString,format))
  elif argv[0] == "alarm2":
    rtc.set_alarm_time(2,datetime.datetime.strptime(dateString,format))
  else:
    print "invalid argument"

# --- on  -- ---------------------------------------------------------------

def on(rtc,argv):
  """
  Turn alarm1/alarm2 on

  Arg: alarm1|alarm2
  """
  if len(argv) == 0:
    print "missing argument"
  elif argv[0] == "alarm1":
    rtc.set_alarm(1,1)
  elif argv[0] == "alarm2":
    rtc.set_alarm(2,1)
    pass
  else:
    print "invalid argument"

# --- off   ----------------------------------------------------------------

def off(rtc,argv):
  """
  Turn alarm1/alarm2 on

  Arg: alarm1|alarm2
  """
  if len(argv) == 0:
    print "missing argument"
  elif argv[0] == "alarm1":
    rtc.set_alarm(1,0)
  elif argv[0] == "alarm2":
    rtc.set_alarm(2,0)
    pass
  else:
    print "invalid argument"

# --- clear  ---------------------------------------------------------------

def clear(rtc,argv):
  """
  Clear alarm1/alarm2-flag

  Arg: alarm1|alarm2
  """
  if len(argv) == 0:
    print "missing argument"
  elif argv[0] == "alarm1":
    rtc.clear_alarm(1)
  elif argv[0] == "alarm2":
    rtc.clear_alarm(2)
  else:
    print "invalid argument"

# --- main program   ------------------------------------------------------

if __name__ == "__main__":
  if len(sys.argv) == 1:
    help()
  else:
    dir = dir()
    command = sys.argv[1]
    if command == 'help':
      help()
    elif command in dir:
      rtc = ds3231.ds3231(1,utc)               # use i2c-1
      exec command+"(rtc,sys.argv[2:])"
    else:
      print "command %s not found!" % command
      help()
