#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-wake-on-rtc
#
# --------------------------------------------------------------------------

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

PACKAGES="python-arrow python-smbus"

if [ -n "$PACKAGES" ] && check_packages $PACKAGES; then
  echo -e "[INFO] installing additional packages" 2>&1
  apt-get update
  apt-get -y install $PACKAGES
fi

# --- install specific files   ----------------------------------------------

echo -e "[INFO] installing project files" 2>&1

rand="$RANDOM"
if [ -f /etc/wake-on-rtc.conf ]; then
  # save current configuration
  mv /etc/wake-on-rtc.conf /etc/wake-on-rtc.conf.$rand
fi

for f in `find $(dirname "$0")/../files/ -type f`; do
  cp "$f" "${f#*files}"
  chown root:root "${f#*files}"
done

chmod 755 /usr/local/sbin/wake-on-rtc.py
chmod 755 /usr/local/sbin/rtcctl
chmod 644 /usr/local/sbin/ds3231.py

chmod 644 /etc/wake-on-rtc.conf
chmod 644 /etc/systemd/system/wake-on-rtc.service
chmod 644 /etc/udev/rules.d/85-hwclock.rules

# restore old configuration
if [ -f /etc/wake-on-rtc.conf.$rand ]; then
  mv -f /etc/wake-on-rtc.conf /etc/wake-on-rtc.conf.new
  mv /etc/wake-on-rtc.conf.$rand /etc/wake-on-rtc.conf
  echo -e "[INFO] new version of configuration file saved to: /etc/wake-on-rtc.conf.new" 2>&1
fi

# --- configure system   ----------------------------------------------------

echo -e "[INFO] configuring /boot/config.txt" 2>&1
echo "dtparam=i2c_arm=on" >> /boot/config.txt
echo "dtoverlay=gpio-poweroff,gpiopin=4" >> /boot/config.txt

echo -e "[INFO] configuring /etc/modules" 2>&1
echo "i2c-dev" >> /etc/modules

echo -e "[INFO] disabling fake-hwclock.service" 2>&1
systemctl disable fake-hwclock.service
systemctl stop    fake-hwclock.service

# --- activate service   ----------------------------------------------------

echo -e "[INFO] enabeling wake-on-rtc.service" 2>&1
systemctl enable wake-on-rtc.service

# --- final configuration is manual   ---------------------------------------

echo "Please edit /etc/wake-on-rtc.conf"
echo "Restart the system to activate changes"
